version: "3.3"
services:
  web_server:
    image: nginx:stable
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
  db_server:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pg-root-pass
